spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/main_database
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    pool:
      max-coonections: 100;
server:
  port: 8443